### ISSUE TITLE
hitting `unreachable!` code when using `Migration.create_table_if_not_exists`

### ISSUE THREAD

**Issue by rippinrobr** [spacekookie/barrel#19]
Hi, I'm attempting to use `Migration.create_table_if_not_exists` and when I do I receive the following stack trace:

```
▶ RUST_BACKTRACE=1 cargo run
    Finished dev [unoptimized + debuginfo] target(s) in 0.17s
     Running `target/debug/csv2api`
Created file AwardsManagers.rs
thread 'main' panicked at 'internal error: entered unreachable code', /Users/robertrowe/.cargo/registry/src/github.com-1ecc6299db9ec823/barrel-0.2.1/src/migration.rs:126:18
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::print
             at libstd/sys_common/backtrace.rs:71
             at libstd/sys_common/backtrace.rs:59
   2: std::panicking::default_hook::{{closure}}
             at libstd/panicking.rs:211
   3: std::panicking::default_hook
             at libstd/panicking.rs:227
   4: <std::panicking::begin_panic::PanicPayload<A> as core::panic::BoxMeUp>::get
             at libstd/panicking.rs:463
   5: core::str::utf8_acc_cont_byte
             at /Users/travis/build/rust-lang/rust/src/libstd/panicking.rs:397
   6: barrel::migration::Migration::create_table_if_not_exists
             at ./<panic macros>:3
   7: csv2api::workers::sql_gen::SQLGen::generate_create_table
             at src/workers/sql_gen.rs:23
   8: csv2api::main
             at src/main.rs:55
   9: std::rt::lang_start::{{closure}}
             at /Users/travis/build/rust-lang/rust/src/libstd/rt.rs:74
  10: std::panicking::try::do_call
             at libstd/rt.rs:59
             at libstd/panicking.rs:310
  11: panic_unwind::dwarf::eh::read_encoded_pointer
             at libpanic_unwind/lib.rs:105
  12: std::alloc::default_oom_hook
             at libstd/panicking.rs:289
             at libstd/panic.rs:374
             at libstd/rt.rs:58
  13: std::rt::lang_start
             at /Users/travis/build/rust-lang/rust/src/libstd/rt.rs:74
  14: csv2api::main
```

Since the line mentioned in the stack trace is `unreachable!` I thought I'd let you know I'm hitting it.  This same code works if I just use the `create_table` method.  Here's the code snippet:

```rust
let mut m = Migration::new();
let cols = columns.clone();
m.create_table_if_not_exists(name, move |t| {
    //t.meta.without_id();
    for cd in &cols {
       let cname: &str = &cd.name;
       t.add_column(cname, cd.data_type.to_database_type());
    }
});
```

I am using:
* rustc 1.28.0-nightly (5d0631a64 2018-05-30)
* on a mac
* here's my cargo.toml as well.
* Let me know if you need anything else from me.

```toml
[package]
name = "csv2api"
version = "0.1.0"
authors = ["Rob Rowe <robrowe04@gmail.com>"]

[dependencies]
actix = "0.5"
barrel = "0.2.1"
clap = "2.31.2"
codegen = { git = "https://github.com/carllerche/codegen" } # Soon on crates.io
csv = "1.0.0"
futures = "0.1"
regex = "1.0.0"
# rusqlite = "0.13.0"
sqlite = "0.23.9"
serde_derive = "1.0.66"
serde_json = "1.0.19"
```
